// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yoceyder.WebUI.Repository.Concrete.EntityFramework;

namespace Yoceyder.WebUI.Migrations
{
    [DbContext(typeof(YoceyderContext))]
    [Migration("20200306123328_tbl_child1")]
    partial class tbl_child1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Child", b =>
                {
                    b.Property<int>("Cocuk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cocuk_AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_AnneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_AnneDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_BabaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_BabaDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_KaldigiYer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_OgrenimDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Tc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_VasiYakinlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_not1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentVasi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Vasi_Id")
                        .HasColumnType("int");

                    b.HasKey("Cocuk_Id");

                    b.HasIndex("ParentVasi_Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Donation", b =>
                {
                    b.Property<int>("Yardim_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParentVasi_Id")
                        .HasColumnType("int");

                    b.Property<string>("Yardim_Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yardim_Miktar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yardim_Tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yardim_Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yardim_Urun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yardim_Vasi_Id")
                        .HasColumnType("int");

                    b.Property<string>("Yardim_Ysvr_Adisoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yardim_Ysvr_Telno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Yardim_Id");

                    b.HasIndex("ParentVasi_Id");

                    b.ToTable("Donation");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Parent", b =>
                {
                    b.Property<int>("Vasi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vasi_AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vasi_Cocuksayisi")
                        .HasColumnType("int");

                    b.Property<string>("Vasi_Dosya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Evdurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vasi_Guncellemetarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vasi_Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vasi_Kayittarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Vasi_Kiramiktari")
                        .HasColumnType("float");

                    b.Property<string>("Vasi_Maas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vasi_Maasmiktari")
                        .HasColumnType("float");

                    b.Property<string>("Vasi_Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Resimyolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Tc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vasi_Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Tbl_Child", b =>
                {
                    b.Property<int>("Cocuk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cockuk_DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cocuk_AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_AnneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_AnneDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_BabaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_BabaDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_KaldigiYer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_OgrenimDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Tc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_VasiYakinlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vasi_Id")
                        .HasColumnType("int");

                    b.HasKey("Cocuk_Id");

                    b.ToTable("Tbl_Child");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Child", b =>
                {
                    b.HasOne("Yoceyder.WebUI.Entity.Parent", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentVasi_Id");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Donation", b =>
                {
                    b.HasOne("Yoceyder.WebUI.Entity.Parent", "Parent")
                        .WithMany("Donations")
                        .HasForeignKey("ParentVasi_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
