// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yoceyder.WebUI.Repository.Concrete.EntityFramework;

namespace Yoceyder.WebUI.Migrations
{
    [DbContext(typeof(YoceyderContext))]
    [Migration("20200304104024_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Child", b =>
                {
                    b.Property<int>("Cocuk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cocuk_AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocuk_Tc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentVasi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Vasi_Id")
                        .HasColumnType("int");

                    b.HasKey("Cocuk_Id");

                    b.HasIndex("ParentVasi_Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Parent", b =>
                {
                    b.Property<int>("Vasi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vasi_AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vasi_Cocuksayisi")
                        .HasColumnType("int");

                    b.Property<string>("Vasi_Dosya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Evdurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vasi_Guncellemetarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vasi_Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vasi_Kayittarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Vasi_Kiramiktari")
                        .HasColumnType("float");

                    b.Property<string>("Vasi_Maas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vasi_Maasmiktari")
                        .HasColumnType("float");

                    b.Property<string>("Vasi_Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Tc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vasi_Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vasi_Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Yoceyder.WebUI.Entity.Child", b =>
                {
                    b.HasOne("Yoceyder.WebUI.Entity.Parent", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentVasi_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
